### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by seajaysec** [jurgen-kluft/go-qmk-keymap#2]
Hey sorry, I'm not super familiar with go so maybe it's obvious but I can't figure out how to get this to run. I've tried `go run main.go /path/to/keymap.c` and just dropping main.go in my project dir and calling it with `go run main.go` but it's not executing.

**Comment by jurgen-kluft** [comment]
This is used as a process, so stdin → stdout.
The first thing to do is to build the executable for your platform/OS. Then if you use VSCode you can follow the details in the README.md (https://github.com/jurgen-kluft/go-qmk-keymap#visual-studio-code-vscode).
On the command-line you could direct the content of your .c file to go-qmk-keymap and write stdout to a new or same file
      `cat unformatted.c | go-qmk-keymap(.exe) > formatted.c`
